# Generated by Django 3.2.9 on 2021-12-14 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('family', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('last_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_tag', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('annotation', models.TextField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='istorii.texttag')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='istorii.person')),
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='istorii.text')),
            ],
            options={
                'db_table': 'action',
                'unique_together': {('person_id', 'text_id')},
            },
        ),
    ]
